// Asynchronous actions

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";


// Synchronous actions

export const SIGNUP_SET_TYPE = "SIGNUP_SET_TYPE";

export const SIGNUP_SET_FIRST_NAME = "SIGNUP_SET_FIRST_NAME"
export const SIGNUP_SET_LAST_NAME = "SIGNUP_SET_LAST_NAME"
export const SIGNUP_SET_USERNAME = "SIGNUP_SET_USERNAME";
export const SIGNUP_SET_PASSWORD = "SIGNUP_SET_PASSWORD";
export const SIGNUP_SET_EMAIL = "SIGNUP_SET_EMAIL";

export const SIGNUP_SET_OHIP = "SIGNUP_SET_OHIP";
export const SIGNUP_SET_SCN = "SIGNUP_SET_SCN";
export const SIGNUP_SET_OWNER = "SIGNUP_SET_OWNER";
export const SIGNUP_SET_DOB = "SIGNUP_SET_DOB";
export const SIGNUP_SET_GENDER = "SIGNUP_SET_GENDER";
export const SIGNUP_SET_RACE = "SIGNUP_SET_RACE";
export const SIGNUP_SET_EDU_LEVEL = "SIGNUP_SET_EDU_LEVEL";
export const SIGNUP_SET_REVIEW = "SIGNUP_SET_REVIEW";
export const SIGNUP_SET_GENERAL = "SIGNUP_SET_GENERAL";
export const SIGNUP_SET_POSTAL = "SIGNUP_SET_POSTAL";

export const SIGNUP_SET_PROFESSION = "SIGNUP_SET_PROFESSION";
export const SIGNUP_SET_LICENSE = "SIGNUP_SET_LICENSE";
export const SIGNUP_SET_WORK_NAME = "SIGNUP_SET_WORK_NAME";
export const SIGNUP_SET_WORK_ADDRESS = "SIGNUP_SET_WORK_ADDRESS";
export const SIGNUP_SET_WORK_CITY = "SIGNUP_SET_WORK_CITY";
export const SIGNUP_SET_WORK_POSTAL = "SIGNUP_SET_WORK_POSTAL";
export const SIGNUP_SET_WORK_PHONE_NUMBER = "SIGNUP_SET_WORK_PHONE_NUMBER";


// ---------- Immunization -------------

// Asynchronous Actions

export const IMMU_PATIENTS_PENDING = "IMMU_PATIENTS_PENDING";
export const IMMU_PATIENTS_SUCCESS = "IMMU_PATIENTS_SUCCESS";

export const IMMU_PATIENT_INFO_PENDING = "IMMU_PATIENT_INFO_PENDING";
export const IMMU_PATIENT_INFO_SUCCESS = "IMMU_PATIENT_INFO_SUCCESS";

export const IMMU_PATIENT_UPDATE_INFO_PENDING = "IMMU_PATIENT_UPDATE_INFO_PENDING";

export const IMMU_PATIENT_ADD_ENTRY_PENDING = "IMMU_PATIENT_ADD_ENTRY_PENDING";
export const IMMU_PATIENT_ADD_ENTRY_SUCCESS = "IMMU_PATIENT_ADD_ENTRY_SUCCESS";

// Synchronous Actions
