// Asynchronous actions

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";


// Synchronous actions

export const SIGNUP_SET_NAME = "SIGNUP_SET_NAME"
export const SIGNUP_SET_CREDENTIALS = "SIGNUP_SET_CREDENTIALS";

export const SIGNUP_SET_OHIP = "SIGNUP_SET_OHIP";
export const SIGNUP_SET_SCN = "SIGNUP_SET_SCN";
export const SIGNUP_SET_OWNER = "SIGNUP_SET_OWNER";
export const SIGNUP_SET_DOB = "SIGNUP_SET_DOB";
export const SIGNUP_SET_GENDER = "SIGNUP_SET_GENDER";
export const SIGNUP_SET_REVIEW = "SIGNUP_SET_REVIEW";
export const SIGNUP_SET_GENERAL = "SIGNUP_SET_GENERAL";

export const SIGNUP_SET_PROFESSION = "SIGNUP_SET_PROFESSION";
export const SIGNUP_SET_LICENSE = "SIGNUP_SET_LICENSE";
export const SIGNUP_SET_PRIMARY_WORK = "SIGNUP_SET_PRIMARY_WORK";
export const SIGNUP_SET_OTHER_WORK = "SIGNUP_SET_OTHER_WORK";