export {
    loginPending,
    loginSuccess,
    loginFail,
    signupPending,
    signupSuccess,
    signupFail,

    signupSetFirstName,
    signupSetLastName,
    signupSetUsername,
    signupSetPassword,
    signupSetEmail,
    
    signupSetOHIP,
    signupSetSCN,
    signupSetOwner,
    signupSetDOB,
    signupSetGender,
    signupSetProfession,
    signupSetLicense,
    signupSetWorkName,
    signupSetWorkAddress,
    signupSetWorkCity,
    signupSetWorkPostal,
    signupSetWorkPhoneNumber,
} from './auth';