export {
    loginPending,
    loginSuccess,
    loginFail,
    signupPending,
    signupSuccess,
    signupFail,

    signupSetOHIP,
    signupSetSCN,
    signupSetOwner,
    signupSetDOB,
    signupSetGender,
    signupSetCredentials,
    signupSetProfession,
    signupSetLicense,
    signupSetName,
    signupSetPrimaryWork,
    signupSetOtherWork,
} from './auth';